
{% set name = "tramway" %}
{% set version = "0.5rc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 80226d3949c210f1c9b22ecb884080f34869a033c3491f40c540cec094bfae7f
  git_url: https://github.com/decbaycomp/tramway.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install .[roi,animate] -vv"

requirements:
  #build:
  #  - pytest-runner
  host:
    - pip
    - python >=3.6
  run:
    - hdf5
    - python >=3.6
    - rwa-python

test:
  imports:
    - tramway
  requires:
    - pytest
  commands:
    - pytest tests/test_core.py
    - pytest tests/test_analyzer.py
    - pytest tests/test_analyzer_pipeline.py::test_LocalHost
  source_files:
    - tests/test_core.py
    - tests/test_analyzer.py
    - tests/test_analyzer_pipeline.py

about:
  home: https://github.com/DecBayComp/TRamWAy
  license: CECILL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'The RAndom Walk AnalYzer: analysis toolbox for localization microscopy data'
  doc_url: https://tramway.readthedocs.io/

extra:
  recipe-maintainers:
    - DecBayComp
