# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests and code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest
          tests/test_core.py
          tests/test_analyzer.py::TestSptDataAccess
          tests/test_analyzer.py::TestTesseller
          tests/test_analyzer.py::TestIndexer
          tests/test_analyzer.py::TestAssignment
          tests/test_analyzer.py::TestSideEffects

  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-cov
        find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
        python -m pip install .
        python -m pytest --cov=./
    - uses: codecov/codecov-action@v1
      #with:
      #  fail_ci_if_error: true
